### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by win10ogod** [esciron/ComfyUI-HunyuanVideoWrapper-Extended#3]
Loading text encoder model (clipL) from: E:\ComfyUI-aki-v1.3\models\clip\clip-vit-large-patch14
!!! Exception during processing !!! Unsupported text encoder type: clipL
Traceback (most recent call last):
  File "E:\ComfyUI-aki-v1.3\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI-aki-v1.3\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI-aki-v1.3\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\ComfyUI-aki-v1.3\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-HunyuanVideoWrapper-Extended\nodes.py", line 457, in loadmodel
    text_encoder_2 = TextEncoder(
                     ^^^^^^^^^^^^
  File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-HunyuanVideoWrapper-Extended\hyvideo\text_encoder\__init__.py", line 197, in __init__
    self.model, self.model_path = load_text_encoder(
                                  ^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-HunyuanVideoWrapper-Extended\hyvideo\text_encoder\__init__.py", line 66, in load_text_encoder
    raise ValueError(f"Unsupported text encoder type: {text_encoder_type}")
ValueError: Unsupported text encoder type: clipL

**Comment by esciron** [comment]
There's problems with the merge, as my original code was written for a way older version. (Tho this error only happens on my tests when using the default llm)
I'll upload a branch with the stable version that lacks some functionalities from the updated original wrapper.

**Comment by esciron** [comment]
Here it is:
https://github.com/esciron/ComfyUI-HunyuanVideoWrapper-Extended/tree/stable

**Comment by win10ogod** [comment]
> Here it is: https://github.com/esciron/ComfyUI-HunyuanVideoWrapper-Extended/tree/stable

new feedback(use llava):
```

Loading text encoder model (llava) from: E:\ComfyUI-aki-v1.3\models\LLM\xtuner_llava-llama-3-8b-v1_1-transformers
Text encoder to dtype: torch.float16
Loading tokenizer (llava) from: E:\ComfyUI-aki-v1.3\models\LLM\xtuner_llava-llama-3-8b-v1_1-transformers
!!! Exception during processing !!! 'NoneType' object has no attribute 'shape'
Traceback (most recent call last):
  File "E:\ComfyUI-aki-v1.3\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI-aki-v1.3\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI-aki-v1.3\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\ComfyUI-aki-v1.3\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-HunyuanVideoWrapper-Extended\nodes.py", line 621, in process
    prompt_embeds, negative_prompt_embeds, attention_mask, negative_attention_mask = encode_prompt(self, prompt, negative_prompt, text_encoder_1)
                                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-HunyuanVideoWrapper-Extended\nodes.py", line 513, in encode_prompt
    prompt_outputs = text_encoder.encode(text_inputs, data_type=data_type, device=device)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-HunyuanVideoWrapper-Extended\hyvideo\text_encoder\__init__.py", line 359, in encode
    outputs = self.model(
              ^^^^^^^^^^^
  File "E:\ComfyUI-aki-v1.3\.ext\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI-aki-v1.3\.ext\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI-aki-v1.3\.ext\Lib\site-packages\transformers\models\llava\modeling_llava.py", line 487, in forward
    inputs_embeds, attention_mask, labels, position_ids = self._merge_input_ids_with_image_features(
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI-aki-v1.3\.ext\Lib\site-packages\transformers\models\llava\modeling_llava.py", line 303, in _merge_input_ids_with_image_features
    num_images, num_image_patches, embed_dim = image_features.shape
                                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'shape'

```
